const AnalyticsActivitiesColumns = {
  "title": "AnalyticsActivitiesColumns",
  "type": "string",
  "enum": [
    "Activity ID",
    "Type",
    "Source",
    "Message ID",
    "Segment ID",
    "Conversation ID",
    "Ticket IDs",
    "Segment",
    "Segment start",
    "Segment end",
    "Direction",
    "Status",
    "Status at activity time",
    "Inbox",
    "Inbox API ID",
    "Inbox at activity time",
    "Inbox API IDs at activity time",
    "Previous inbox IDs",
    "Message date",
    "Autoreply",
    "Reaction time",
    "Total reply time",
    "Handle time",
    "Response time",
    "Stage resolution time",
    "Replies to resolution",
    "Ticket resolution time",
    "Ticket replies to resolution",
    "Attributed to",
    "Assignee",
    "Author",
    "Contact name",
    "Contact handle",
    "Account names",
    "From",
    "To",
    "Cc",
    "Bcc",
    "Extract",
    "Tags",
    "Tag API IDs",
    "Tags at activity time",
    "Tag API IDs at activity time",
    "Tag application duration",
    "Activity API ID",
    "Message API ID",
    "Comment API ID",
    "Conversation API ID",
    "Message original ID",
    "New Conversation",
    "First response",
    "Business hours",
    "Subject",
    "Account name",
    "Survey rating",
    "Survey comment",
    "Segment closed",
    "Segment contains messages",
    "Last segment activity",
    "Added tag",
    "Added tag API ID",
    "Removed tag",
    "Removed tag API ID",
    "Segment cumulative teammates",
    "Ticket status name",
    "Ticket status category",
    "Time spent in Ticket Status",
    "Transitions to Ticket Status",
    "Smart QA score",
    "Custom Field",
    "Updated Custom Field"
  ],
  "x-readme-ref-name": "AnalyticsActivitiesColumns"
} as const;
export default AnalyticsActivitiesColumns
