const CustomMessage = {
  "required": [
    "sender",
    "body"
  ],
  "properties": {
    "sender": {
      "type": "object",
      "description": "Data of the sender",
      "required": [
        "handle"
      ],
      "properties": {
        "contact_id": {
          "type": "string",
          "description": "ID of the contact in Front corresponding to the sender"
        },
        "name": {
          "type": "string",
          "description": "Name of the sender"
        },
        "handle": {
          "type": "string",
          "description": "Handle of the sender. It can be any string used to uniquely identify the sender. **Important:** When sending a phone number, include a country code preceded by a plus (+) sign. For example, +33 for France. If you do not send a country code or include a plus sign, Front will normalize your phone number to the USA (+1)."
        }
      }
    },
    "subject": {
      "type": "string",
      "description": "Subject of the message"
    },
    "body": {
      "type": "string",
      "description": "Body of the message"
    },
    "body_format": {
      "type": "string",
      "description": "Format of the message body. Can be `markdown` (default) or `html`.",
      "enum": [
        "html",
        "markdown"
      ],
      "default": "markdown"
    },
    "metadata": {
      "type": "object",
      "properties": {
        "thread_ref": {
          "type": "string",
          "description": "Reference which will be used to thread messages. If omitted, Front threads by sender instead. This reference is unique to custom channels. If you supply a reference generated by another endpoint, the message will not thread into the same conversation."
        },
        "headers": {
          "type": "object",
          "description": "Custom object where any internal information can be stored",
          "additionalProperties": true
        }
      }
    },
    "attachments": {
      "description": "Binary data of attached files. Must use `Content-Type: multipart/form-data` if specified. See [example](https://gist.github.com/hdornier/e04d04921032e98271f46ff8a539a4cb) or read more about [Attachments](https://dev.frontapp.com/docs/attachments-1).  Max 25 MB.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "binary"
      }
    }
  },
  "title": "CustomMessage",
  "x-readme-ref-name": "CustomMessage",
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#"
} as const;
export default CustomMessage
