import Attachment from './Attachment.js';
import RecipientResponse from './RecipientResponse.js';

const MessageResponse = {
  "type": "object",
  "properties": {
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "string",
          "description": "Link to resource",
          "examples": [
            "https://yourCompany.api.frontapp.com/messages/msg_1q15qmtq"
          ]
        },
        "related": {
          "type": "object",
          "properties": {
            "conversation": {
              "type": "string",
              "description": "Link to message conversation",
              "examples": [
                "https://yourCompany.api.frontapp.com/conversations/cnv_yo1kg5q"
              ]
            },
            "message_replied_to": {
              "type": "string",
              "description": "Link to message this message replied to",
              "examples": [
                "https://yourCompany.api.frontapp.com/messages/msg_2y67qldq"
              ]
            },
            "message_seen": {
              "type": "string",
              "description": "Link to message seen information",
              "examples": [
                "https://yourCompany.api.frontapp.com/messages/msg_1q15qmtq/seen"
              ]
            }
          }
        }
      }
    },
    "id": {
      "type": "string",
      "description": "Unique identifier of the message",
      "examples": [
        "msg_1q15qmtq"
      ]
    },
    "message_uid": {
      "type": "string",
      "description": "Secondary unique identifier of a message. Generated by Front on message creation. Learn more at about the [message UID](https://dev.frontapp.com/reference/messages#creating-a-new-message).",
      "examples": [
        "1eab543f84a0785f7b6b8967cck18f4d"
      ]
    },
    "type": {
      "type": "string",
      "description": "Type of the message\n\n`call` `custom` `email` `facebook` `front_chat` `googleplay` `intercom` `internal` `phone-call` `sms` `tweet` `tweet_dm` `whatsapp` `yalo_wha`",
      "enum": [
        "call",
        "custom",
        "email",
        "facebook",
        "front_chat",
        "googleplay",
        "intercom",
        "internal",
        "phone-call",
        "sms",
        "tweet",
        "tweet_dm",
        "whatsapp",
        "yalo_wha"
      ],
      "examples": [
        "email"
      ]
    },
    "is_inbound": {
      "type": "boolean",
      "description": "Whether or not the message has been received or sent",
      "examples": [
        false
      ]
    },
    "draft_mode": {
      "type": [
        "string",
        "null"
      ],
      "description": "If the message is a draft, describes the draft mode. Can be 'private' (draft is visible to the author only) or 'shared' (draft is visible to all teammates with access to the conversation).\n\n`shared` `private`",
      "enum": [
        "shared",
        "private"
      ],
      "examples": [
        "shared"
      ]
    },
    "error_type": {
      "type": "string",
      "description": "Type of the error when the draft failed to be sent"
    },
    "version": {
      "type": "string",
      "description": "The current version of the message in Front",
      "examples": [
        "551ba368f3e7803cce51503ee3e58ef0-26028-1701804863304-945c"
      ]
    },
    "created_at": {
      "type": "number",
      "description": "The timestamp when the message was sent or received",
      "examples": [
        1701292639
      ]
    },
    "subject": {
      "type": "string",
      "description": "Subject of the message",
      "examples": [
        "Jim's pranks are getting out of hand"
      ]
    },
    "blurb": {
      "type": "string",
      "description": "Preview of the message body",
      "examples": [
        "It's high time we discuss the pranking culture in the office"
      ]
    },
    "author": {
      "type": "object",
      "description": "Front teammate who sent this message",
      "required": [
        "_links",
        "id",
        "email",
        "username",
        "first_name",
        "last_name",
        "license_type",
        "is_admin",
        "is_available",
        "is_blocked",
        "type",
        "custom_fields"
      ],
      "properties": {
        "_links": {
          "type": "object",
          "properties": {
            "self": {
              "type": "string",
              "description": "Link to resource",
              "examples": [
                "https://yourCompany.api.frontapp.com/teammates/tea_6r55a"
              ]
            },
            "related": {
              "type": "object",
              "properties": {
                "inboxes": {
                  "type": "string",
                  "description": "Link to teammate's inboxes",
                  "examples": [
                    "https://yourCompany.api.frontapp.com/teammates/tea_6r55a/inboxes"
                  ]
                },
                "conversations": {
                  "type": "string",
                  "description": "Link to teammate's conversations",
                  "examples": [
                    "https://yourCompany.api.frontapp.com/teammates/tea_6r55a/conversations"
                  ]
                },
                "botSource": {
                  "type": "string",
                  "description": "Link to the source resource of the bot (e.g. rule)",
                  "examples": [
                    "https://yourCompany.api.frontapp.com/rules/rul_6r55a"
                  ]
                }
              }
            }
          }
        },
        "id": {
          "type": "string",
          "description": "Unique identifier of the teammate",
          "examples": [
            "tea_6r55a"
          ]
        },
        "email": {
          "type": "string",
          "description": "Email address of the teammate",
          "examples": [
            "michael.scott@dundermifflin.com"
          ]
        },
        "username": {
          "type": "string",
          "description": "Username of the teammate (used for \"@\" mentions)",
          "examples": [
            "PrisonMike"
          ]
        },
        "first_name": {
          "type": "string",
          "description": "First name of the teammate",
          "examples": [
            "Michael"
          ]
        },
        "last_name": {
          "type": "string",
          "description": "Last name of the teammate",
          "examples": [
            "Scott"
          ]
        },
        "is_admin": {
          "type": "boolean",
          "description": "Whether or not the teammate is an admin in your company",
          "examples": [
            true
          ]
        },
        "is_available": {
          "type": "boolean",
          "description": "Whether or not the teammate is available",
          "examples": [
            false
          ]
        },
        "is_blocked": {
          "type": "boolean",
          "description": "Whether or not the teammate account has been blocked",
          "examples": [
            false
          ]
        },
        "type": {
          "type": "string",
          "description": "Type of the teammate, normal teammates are denoted as \"user\", while visitors are denoted as \"visitor\".\nBot users are denoted by their parent resource type.\nThe following bot types are available:\n  * ai: acting on behalf of an AI\n  * api: acting on behalf of OAuth clients\n  * application: acting on behalf of an Application\n  * bulk_reply: acting on behalf of a Bulk Reply\n  * csat: used for authoring CSAT response comments\n  * integration: acting on behalf of an Integration\n  * macro: acting on behalf of a Macro, author of comments and drafts\n  * rule: acting on behalf of a Rule, author of comments and drafts\n  * smart_csat: acting on behalf of a Smart CSAT\n\n\n`user` `visitor` `ai` `api` `application` `bulk_reply` `csat` `integration` `macro` `rule` `smart_csat`",
          "enum": [
            "user",
            "visitor",
            "ai",
            "api",
            "application",
            "bulk_reply",
            "csat",
            "integration",
            "macro",
            "rule",
            "smart_csat"
          ]
        },
        "custom_fields": {
          "description": "Custom fields for this teammate",
          "type": "object",
          "additionalProperties": true
        }
      }
    },
    "recipients": {
      "type": "array",
      "items": RecipientResponse
    },
    "body": {
      "type": "string",
      "description": "Body of the message",
      "examples": [
        "<p>Hi there,</p><p>I wanted to let you know that I'm suggesting an update to <a href='https://dundermifflin.com/privacy/pranks'>Dunder Mifflin's Pranking Policy</a> to provide non-humorous employees greater control over their well-being in the office.</p>"
      ]
    },
    "text": {
      "type": "string",
      "description": "Text version of the body for email messages",
      "examples": [
        "Hi there,\\n\\nI wanted to let you know that I'm suggesting an update to Dunder Mifflin's Pranking Policy (https://dundermifflin.com/privacy/pranks) to provide non-humorous employees greater control over their well-being in the office."
      ]
    },
    "attachments": {
      "type": "array",
      "items": Attachment,
      "description": "List of files attached to the message"
    },
    "signature": {
      "description": "The signature attached to this message",
      "type": "object",
      "required": [
        "_links",
        "id",
        "name",
        "body",
        "sender_info",
        "is_private",
        "is_visible_for_all_teammate_channels",
        "is_default",
        "channel_ids"
      ],
      "properties": {
        "_links": {
          "type": "object",
          "properties": {
            "self": {
              "type": "string",
              "description": "Link to resource",
              "examples": [
                "https://yourCompany.api.frontapp.com/signatures/sig_6rrv2"
              ]
            },
            "related": {
              "type": "object",
              "properties": {
                "owner": {
                  "type": "string",
                  "description": "Link to signature's owner (either a team or teammate)",
                  "examples": [
                    "https://yourCompany.api.frontapp.com/teams/tim_k30"
                  ]
                }
              }
            }
          }
        },
        "id": {
          "type": "string",
          "description": "Unique identifier of the signature",
          "examples": [
            "sig_6rrv2"
          ]
        },
        "name": {
          "type": [
            "string",
            "null"
          ],
          "description": "Name of the signature",
          "examples": [
            "Finer Things Club signature"
          ]
        },
        "body": {
          "type": "string",
          "description": "Body of the signature",
          "examples": [
            "<div>—<br />{{user.name}}<br />No paper, no plastic, and no work talk allowed<br /></div>"
          ]
        },
        "sender_info": {
          "type": [
            "string",
            "null"
          ],
          "description": "Sender info of the signature"
        },
        "is_visible_for_all_teammate_channels": {
          "type": "boolean",
          "description": "Whether or not the signature is available in teammate channels.",
          "examples": [
            true
          ]
        },
        "is_default": {
          "type": "boolean",
          "description": "Whether the signature is the default signature for the team or teammate.",
          "examples": [
            false
          ]
        },
        "is_private": {
          "type": "boolean",
          "description": "Whether the signature is private to the teammate.",
          "examples": [
            true
          ]
        },
        "channel_ids": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string",
            "description": "List of channels the signature is available in. If belonging to a teammate, represents all channels this can be used in. If belonging to a team, represents all team channels this can be used in. If null, there are no restrictions."
          }
        }
      }
    },
    "metadata": {
      "type": "object",
      "description": "Optional metadata about the message",
      "properties": {
        "intercom_url": {
          "type": "string",
          "description": "For `intercom` messages only. URL of the Intercom conversation the message is coming from.",
          "examples": [
            "http://intercom.com"
          ]
        },
        "duration": {
          "type": "integer",
          "description": "For `truly-call` messages only. Length of the call in seconds.",
          "examples": [
            189
          ]
        },
        "have_been_answered": {
          "type": "boolean",
          "description": "For `truly-call` messages only. Whether or not the call have been answered.",
          "examples": [
            false
          ]
        },
        "external_id": {
          "type": "string",
          "description": "For `tweet` or 'custom' (partner channel token authenticated) messages only. Unique message identifier in the underlying provider (Twitter or Partner). For custom messages, only present for partner channel token authenticated requests.",
          "examples": [
            "dkd84992kduo903"
          ]
        },
        "twitter_url": {
          "type": "string",
          "description": "For `tweet` messages only. URL of the tweet.",
          "examples": [
            "https://twitter.com"
          ]
        },
        "is_retweet": {
          "type": "boolean",
          "description": "For `tweet` messages only. Whether or not the tweet is a retweet.",
          "examples": [
            true
          ]
        },
        "have_been_retweeted": {
          "type": "boolean",
          "description": "For `tweet` messages only. Whether or not the tweet have been retweeted.",
          "examples": [
            true
          ]
        },
        "have_been_favorited": {
          "type": "boolean",
          "description": "For `tweet` messages only. Whether or not the tweet have been favorited.",
          "examples": [
            false
          ]
        },
        "thread_ref": {
          "type": "string",
          "description": "For `custom` messages only. Custom reference which is used to thread messages.",
          "examples": [
            "t0930k9000-394"
          ]
        },
        "headers": {
          "type": "object",
          "description": "For `custom` messages only. Custom object holding internal information.",
          "additionalProperties": true
        },
        "chat_visitor_url": {
          "type": "string",
          "description": "For `front_chat` messages only. Source URL from the chat widget when sending a message.",
          "examples": [
            "https://yourCompany.com/products"
          ]
        }
      }
    }
  },
  "title": "MessageResponse",
  "x-readme-ref-name": "MessageResponse",
  "$schema": "http://json-schema.org/draft-04/schema#"
} as const;
export default MessageResponse
